package CinemaInc;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jason
 */
public class MainMenuUI extends javax.swing.JFrame { //MainMenuUI class initializes and contains all methods related to
                                                    //the Main Menu Form

    //New Current, Currency, Clock, Image and Search objects created
    Clock menuClock = new Clock();
    Currency currency = new Currency();
    Current current = new Current();
    Image image = new Image();
    Search search = new Search();

    String loa = current.getLoa(); //Stores current users level of access
    String[][] closestEvents = new String[3][3]; //Stores events to be displayed on form
    int currencyIndex = currency.getCurrencyIndex(); //Stores index representing users chosen currency

    /**
     * Constructor method for MainMenuUI class
     * 
     * Creates new form MainMenuUI
     * Sets form features depending on users level of access 
     * Starts clock 
     * Displays events + icons 
     * Initializes currency
     */
    public MainMenuUI() {
        initComponents();

        setLocationRelativeTo(null);

        setFeatures();

        menuClock.setLabel(timeLbl);
        menuClock.setFrame(this);
        menuClock.start();

        closestEvents = getClosestEvents();
        setEvents(closestEvents);

        String[] eventTypes = {closestEvents[0][2], closestEvents[1][2], closestEvents[2][2]};
        image.setMainMenuIcons(eventTypes, image1Lbl, image2Lbl, image3Lbl);

        currencyBox.setSelectedIndex(currencyIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinemaLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        currencyBox = new javax.swing.JComboBox<>();
        currencyLbl = new javax.swing.JLabel();
        event1Lbl = new javax.swing.JLabel();
        event3Lbl = new javax.swing.JLabel();
        event2Lbl = new javax.swing.JLabel();
        image1Lbl = new javax.swing.JLabel();
        image2Lbl = new javax.swing.JLabel();
        image3Lbl = new javax.swing.JLabel();
        date1Lbl = new javax.swing.JLabel();
        date2Lbl = new javax.swing.JLabel();
        date3Lbl = new javax.swing.JLabel();
        goTo1Btn = new javax.swing.JButton();
        goTo2Btn = new javax.swing.JButton();
        goTo3Btn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        middleBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        eventTitleTxt = new javax.swing.JTextField();
        eventDateTxt = new javax.swing.JTextField();
        eventTimeTxt = new javax.swing.JTextField();
        eventDateLbl = new javax.swing.JLabel();
        eventTimeLbl = new javax.swing.JLabel();
        eventTitleLbl = new javax.swing.JLabel();
        quickSearchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cinemaLbl.setFont(new java.awt.Font("Tahoma", 3, 60)); // NOI18N
        cinemaLbl.setText("Cinema Inc.");

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Main Menu");

        timeLbl.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        timeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLbl.setText("00:00");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        welcomeLbl.setText("Welcome, Forename Surname!");

        currencyBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currencyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pound", "Dollar", "Euro" }));

        currencyLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        currencyLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currencyLbl.setText("Currency: ");

        event1Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        event1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        event1Lbl.setText("Event 1");
        event1Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        event3Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        event3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        event3Lbl.setText("Event 3");
        event3Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        event2Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        event2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        event2Lbl.setText("Event 2");
        event2Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        image1Lbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        image1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image1Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        image2Lbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        image2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image2Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        image3Lbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        image3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image3Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date1Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date1Lbl.setText("Event 1 Date");
        date1Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date2Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date2Lbl.setText("Event 2 Date");
        date2Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date3Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date3Lbl.setText("Event 3 Date");
        date3Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        goTo1Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        goTo1Btn.setText("Go To");
        goTo1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goTo1BtnActionPerformed(evt);
            }
        });

        goTo2Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        goTo2Btn.setText("Go To");
        goTo2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goTo2BtnActionPerformed(evt);
            }
        });

        goTo3Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        goTo3Btn.setText("Go To ");
        goTo3Btn.setToolTipText("");
        goTo3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goTo3BtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        searchBtn.setText("Search For Event ");
        searchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        middleBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        middleBtn.setText("View My Basket");
        middleBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        editBtn.setText("Edit My Account");
        editBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quick Search: ");

        eventTitleTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        eventDateTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        eventTimeTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eventTimeTxt.setToolTipText("");

        eventDateLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eventDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventDateLbl.setText("Event Date");

        eventTimeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eventTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventTimeLbl.setText("Event Time");

        eventTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eventTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventTitleLbl.setText("Event Title");
        eventTitleLbl.setToolTipText("");

        quickSearchBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        quickSearchBtn.setText("Go");
        quickSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cinemaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currencyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(goTo1Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(event1Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date1Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(image1Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(event2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(image2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(date2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goTo2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(middleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(event3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(image3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(date3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goTo3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eventTitleTxt)
                            .addComponent(eventTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eventDateTxt)
                            .addComponent(eventDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eventTimeTxt)
                            .addComponent(eventTimeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(quickSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinemaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(currencyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(currencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(event2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(event3Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(image3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(event1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(image1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date1Lbl)
                            .addComponent(date3Lbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goTo1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(goTo2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goTo3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eventDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eventTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eventTimeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventDateTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventTimeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(quickSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (loa.equals("customer")) { //If user is a customer...
            setCurrency(); //Set chosen currency
        }

        current.setCurrentForm("Search For Event"); //Sets currentForm in Current class to "Search For Event"

        menuClock.stopClock();
        EventSearchUI eventSearchForm = new EventSearchUI(); //New EventSearchUI object created
        eventSearchForm.setVisible(true);
        dispose(); //Current form disposed of
    }//GEN-LAST:event_searchBtnActionPerformed

    private void middleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleBtnActionPerformed
        if (loa.equals("customer")) { //If user is a customer...
            setCurrency(); //Set chosen currency

            current.setCurrentForm("Basket"); //Sets currentForm in Current class to "Basket"

            menuClock.stopClock();
            BasketUI basketForm = new BasketUI(); //New BasketUI object created
            basketForm.setVisible(true);
            dispose(); //Current form disposed of
        }

        if (loa.equals("manager")) { //If user is a manager...
            current.setCurrentForm("Create An Account"); //Sets currentForm in Current class to "Create An Account"

            menuClock.stopClock();
            AccountUI createAccountForm = new AccountUI(); //New AccountUI object created
            createAccountForm.setVisible(true);
            dispose(); //Current form disposed of
        }
    }//GEN-LAST:event_middleBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (loa.equals("customer")) { //If user is a customer...
            setCurrency(); //Set chosen currency
        }

        current.setCurrentForm("Account Details"); //Sets currentForm in Current class to "Account Details"

        menuClock.stopClock();
        AccountUI accountDetailsForm = new AccountUI(); //New AccountUI object created
        accountDetailsForm.setVisible(true);
        dispose(); //Current form disposed of
    }//GEN-LAST:event_editBtnActionPerformed

    private void quickSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSearchBtnActionPerformed
        //Stores users inputted event title, date and time
        String eventTitle = eventTitleTxt.getText();
        String eventDate = eventDateTxt.getText();
        String eventTime = eventTimeTxt.getText();

        boolean searchSuccess = search.quickSearch(eventTitle, eventDate, eventTime);

        if (searchSuccess == true) { //If event is found...

            if (loa.equals("customer")) { //If user is a customer...
                setCurrency(); //Set chosen currency
            }

            current.setCurrentForm("Event Info"); //Sets currentForm in Current class to "Event Info"

            menuClock.stopClock();
            EventInfoUI eventInfo = new EventInfoUI(); //New EventInfoUI object created
            eventInfo.setVisible(true);
            dispose(); //Current form disposed of

        } else { //If event not found...
            JOptionPane.showMessageDialog(null, "This event could not be found. Please make sure title, date and time are correct.", "Event Not Found", JOptionPane.ERROR_MESSAGE);
            eventTitleTxt.setText("");
            eventDateTxt.setText("");
            eventTimeTxt.setText("");
        }
    }//GEN-LAST:event_quickSearchBtnActionPerformed

    private void goTo1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goTo1BtnActionPerformed
        goTo(closestEvents[0][3]);
    }//GEN-LAST:event_goTo1BtnActionPerformed

    private void goTo2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goTo2BtnActionPerformed
        goTo(closestEvents[1][3]);
    }//GEN-LAST:event_goTo2BtnActionPerformed

    private void goTo3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goTo3BtnActionPerformed
        goTo(closestEvents[2][3]);
    }//GEN-LAST:event_goTo3BtnActionPerformed

    /**
     * Sets the forms features depending on the current users level of access
     */
    public void setFeatures() {
        String[] currentUserDetails = new String[11]; //Stores current users details as an array
        currentUserDetails = current.getCurrentUserDetails();

        welcomeLbl.setText("Welcome, " + currentUserDetails[3] + " " + currentUserDetails[4] + "!");

        if (loa.equals("worker")) { //If user is a worker...
            currencyLbl.setVisible(false);
            currencyBox.setVisible(false);
            currencyBox.setEnabled(false);
            middleBtn.setVisible(false);
            middleBtn.setEnabled(false);
        }

        if (loa.equals("manager")) { //If user is a manager...
            currencyLbl.setVisible(false);
            currencyBox.setVisible(false);
            currencyBox.setEnabled(false);
            middleBtn.setText("Create Accounts");
        }

    }

    /**
     * Collects the 3 closest upcoming events from the events file
     * into a 2D array
     * 
     * @return 2D array containing the 3 closest events
     */
    public String[][] getClosestEvents() {
        int numRecords = Search.countRecords("events.txt"); //Stores number of records currently in events file
        String[][] allEvents = new String[numRecords][8]; //Stores all event records in events file as a 2D array
        String[][] closestEvents = new String[3][4]; //Stores the 3 closest events as a 2D array

        Sort sort = new Sort(); //New Sort object created

        allEvents = search.getAllEvents(numRecords);
        sort.eventsToAscendingOrder(allEvents, numRecords, 8, 4); //allEvents sorted to ascending order of date

        for (int i = 0; i < 3; i++) { //For 3 top events in allEvents[] (3 closest events)
            closestEvents[i][0] = allEvents[i][1];
            closestEvents[i][1] = allEvents[i][4];
            closestEvents[i][2] = allEvents[i][2];
            closestEvents[i][3] = allEvents[i][0];
        }

        return closestEvents;
    }

    /**
     * Displays 3 closest upcoming events to the form
     * 
     * @param events 3 closest events as a 2D array
     */
    public void setEvents(String[][] events) {
        event1Lbl.setText(events[0][0]);
        date1Lbl.setText(events[0][1]);

        event2Lbl.setText(events[1][0]);
        date2Lbl.setText(events[1][1]);

        event3Lbl.setText(events[2][0]);
        date3Lbl.setText(events[2][1]);
    }

    /**
     * Takes a user to the event they selected out of the 3 closest events displayed
     * 
     * @param eventID primary key of event selected by user
     */
    public void goTo(String eventID) {
        int numRecords = search.countRecords("events.txt"); //Stores number of records currently in events file
        String chosenEvent[] = search.eventBinarySearch(eventID, numRecords); //Stores details of event as an array
        int index; //Stores index of users chosen currency

        if (chosenEvent[0] != null) { //If array isnt empty (event found)...

            if (loa.equals("customer")) { //If user is a customer...
                index = currencyBox.getSelectedIndex();
                currency.setCurrencyIndex(index); //Sets currencyIndex in Currency class to index
            }

            current.setCurrentEvent(chosenEvent); //Sets currentEvent in Current class to chosenEvent
            current.setCurrentForm("Closest Event Info"); //Sets currentForm in Current class to "Closest Event Info"
            
            menuClock.stopClock();
            EventInfoUI eventInfoForm = new EventInfoUI(); //New EventInfoUI object created
            eventInfoForm.setVisible(true);
            dispose(); //Current form disposed of
            
        } else { //If array is empty (event not found)...
            JOptionPane.showMessageDialog(null, "Sorry, this event could not be found.", "Error!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * Sets a users chosen currency
     */
    public void setCurrency() {
        int index; //Stores index of the chosen currency
        index = currencyBox.getSelectedIndex();
        currency.setCurrencyIndex(index); //Sets currencyIndex in Currency class to index
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinemaLbl;
    private javax.swing.JComboBox<String> currencyBox;
    private javax.swing.JLabel currencyLbl;
    private javax.swing.JLabel date1Lbl;
    private javax.swing.JLabel date2Lbl;
    private javax.swing.JLabel date3Lbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel event1Lbl;
    private javax.swing.JLabel event2Lbl;
    private javax.swing.JLabel event3Lbl;
    private javax.swing.JLabel eventDateLbl;
    private javax.swing.JTextField eventDateTxt;
    private javax.swing.JLabel eventTimeLbl;
    private javax.swing.JTextField eventTimeTxt;
    private javax.swing.JLabel eventTitleLbl;
    private javax.swing.JTextField eventTitleTxt;
    private javax.swing.JButton goTo1Btn;
    private javax.swing.JButton goTo2Btn;
    private javax.swing.JButton goTo3Btn;
    private javax.swing.JLabel image1Lbl;
    private javax.swing.JLabel image2Lbl;
    private javax.swing.JLabel image3Lbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton middleBtn;
    private javax.swing.JButton quickSearchBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
