package CinemaInc;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jason
 */
public class SeatingPlanUI extends javax.swing.JFrame { //SeatingPlanUI class initalizes and contains all methods
                                                       //related to the Seat Selection Form

    //New Booking, BookingTimer, Clock, Current, Search
    //and Timer objects created
    Booking booking = new Booking();
    BookingTimer secondsLeft = new BookingTimer();
    Clock seatingPlanClock = new Clock();
    Current current = new Current();
    Search search = new Search();
    Timer bookingTimer = new Timer();

    String loa = current.getLoa(); //Stores current users level of access
    String currentForm = current.getCurrentForm(); //Stores forms current purpose

    //Stores amount of seconds customer has left to book tickets
    int timeLeft = secondsLeft.getSecondsLeft();
    String minutes; //Stores number of minutes customer has left as a String
    String seconds; //Stores number of seconds customer has left as a String

    //New TimerTask object created
    TimerTask task = new TimerTask() {
        //run() method contains task for timer - runs once every second
        public void run() {

            timeLeft = timeLeft - 1;

            if (timeLeft == -1) { //If customer has run out of time...
                bookingTimer.cancel();
                secondsLeft.resetSecondsLeft(); //Resets secondsLeft in BookingTimer class to 300 seconds (5 minutes)

                JOptionPane.showMessageDialog(null, "Sorry, you have run out of time.", "Timed Out!", JOptionPane.ERROR_MESSAGE);

                //Clears variables + currently selected seats in Booking class
                booking.emptyBooking();
                booking.emptySeats();
                //Clears currentEvent[] in Current class
                current.removeCurrentEvent();

                seatingPlanClock.stopClock();

                //If form being used to add tickets to basket...
                if (currentForm.equals("Booking Seating Plan")) {
                    current.setCurrentForm("Main Menu"); //Sets currentForm in Current class to "Main Menu"

                    MainMenuUI mainMenuForm = new MainMenuUI(); //New MainMenuUI object created
                    mainMenuForm.setVisible(true);
                }

                //If form being used to edit tickets already in basket...
                if (currentForm.equals("Edit Booking Seating Plan")) {
                    current.setCurrentForm("Basket"); //Sets currentForm in Current class to "Basket"

                    BasketUI basketForm = new BasketUI(); //New BasketUI object created
                    basketForm.setVisible(true);
                }

                dispose(); //Current form disposed of
            }

            //Minutes left is result of time left divided by 60 (seconds)
            minutes = String.valueOf(timeLeft / 60);
            //Seconds left is remainder of time left divided by 60 (seconds)
            seconds = String.valueOf(timeLeft % 60);

            if (seconds.length() == 1) { //If seconds in single digits...
                seconds = 0 + seconds;
            }

            timerLbl.setText("Time Left: " + minutes + ":" + seconds);
        }
    };

    /**
     * Constructor method for SeatingPlanUI class
     *
     * Creates new form SeatingPlanUI 
     * Sets form features depending on forms current purpose 
     * Disables buttons representing previously booked seats 
     * Starts clock 
     * If form is being used to book seats/edit basket item, starts booking timer
     */
    public SeatingPlanUI() {
        initComponents();

        setLocationRelativeTo(null);

        setFeatures();

        generateSeatingPlan();

        seatingPlanClock.setLabel(timeLbl);
        seatingPlanClock.setFrame(this);
        seatingPlanClock.start();

        if (currentForm.equals("Booking Seating Plan") || currentForm.equals("Edit Booking Seating Plan")) {
            bookingTimer.schedule(task, 1000, 1000);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        cinemaLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        timerLbl = new javax.swing.JLabel();
        eventTitleLbl = new javax.swing.JLabel();
        seatingPlanPanel = new javax.swing.JPanel();
        screenLbl = new javax.swing.JLabel();
        A5Btn = new javax.swing.JButton();
        A6Btn = new javax.swing.JButton();
        A3Btn = new javax.swing.JButton();
        A4Btn = new javax.swing.JButton();
        A7Btn = new javax.swing.JButton();
        A8Btn = new javax.swing.JButton();
        aLbl = new javax.swing.JLabel();
        bLbl = new javax.swing.JLabel();
        B3Btn = new javax.swing.JButton();
        B4Btn = new javax.swing.JButton();
        B5Btn = new javax.swing.JButton();
        B6Btn = new javax.swing.JButton();
        B7Btn = new javax.swing.JButton();
        B8Btn = new javax.swing.JButton();
        B2Btn = new javax.swing.JButton();
        B9Btn = new javax.swing.JButton();
        cLbl = new javax.swing.JLabel();
        C2Btn = new javax.swing.JButton();
        C3Btn = new javax.swing.JButton();
        C4Btn = new javax.swing.JButton();
        C5Btn = new javax.swing.JButton();
        C6Btn = new javax.swing.JButton();
        C7Btn = new javax.swing.JButton();
        C8Btn = new javax.swing.JButton();
        C9Btn = new javax.swing.JButton();
        dLbl = new javax.swing.JLabel();
        D2Btn = new javax.swing.JButton();
        D3Btn = new javax.swing.JButton();
        D4Btn = new javax.swing.JButton();
        D5Btn = new javax.swing.JButton();
        D6Btn = new javax.swing.JButton();
        D7Btn = new javax.swing.JButton();
        D8Btn = new javax.swing.JButton();
        D9Btn = new javax.swing.JButton();
        eLbl = new javax.swing.JLabel();
        E2Btn = new javax.swing.JButton();
        E3Btn = new javax.swing.JButton();
        E4Btn = new javax.swing.JButton();
        E5Btn = new javax.swing.JButton();
        E6Btn = new javax.swing.JButton();
        E7Btn = new javax.swing.JButton();
        E8Btn = new javax.swing.JButton();
        E9Btn = new javax.swing.JButton();
        E10Btn = new javax.swing.JButton();
        E1Btn = new javax.swing.JButton();
        fLbl = new javax.swing.JLabel();
        F1Btn = new javax.swing.JButton();
        F2Btn = new javax.swing.JButton();
        F3Btn = new javax.swing.JButton();
        F4Btn = new javax.swing.JButton();
        F5Btn = new javax.swing.JButton();
        F6Btn = new javax.swing.JButton();
        F7Btn = new javax.swing.JButton();
        F8Btn = new javax.swing.JButton();
        F9Btn = new javax.swing.JButton();
        F10Btn = new javax.swing.JButton();
        oneLbl = new javax.swing.JLabel();
        twoLbl = new javax.swing.JLabel();
        threeLbl = new javax.swing.JLabel();
        fourLbl = new javax.swing.JLabel();
        fiveLbl = new javax.swing.JLabel();
        sixLbl = new javax.swing.JLabel();
        tenLbl = new javax.swing.JLabel();
        nineLbl = new javax.swing.JLabel();
        eightLbl = new javax.swing.JLabel();
        sevenLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        finalizeBtn = new javax.swing.JButton();
        seatsLbl = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cinemaLbl.setFont(new java.awt.Font("Tahoma", 3, 60)); // NOI18N
        cinemaLbl.setText("Cinema Inc.");

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Booking");

        timeLbl.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        timeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLbl.setText("00:00");

        timerLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        timerLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timerLbl.setText("Time Left: 0:00");
        timerLbl.setToolTipText("");
        timerLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        eventTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        eventTitleLbl.setText("Event Title + No. of Tickets Being Booked");
        eventTitleLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        seatingPlanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        screenLbl.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        screenLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenLbl.setText("Screen/Stage");
        screenLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5BtnActionPerformed(evt);
            }
        });

        A6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6BtnActionPerformed(evt);
            }
        });

        A3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3BtnActionPerformed(evt);
            }
        });

        A4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4BtnActionPerformed(evt);
            }
        });

        A7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7BtnActionPerformed(evt);
            }
        });

        A8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8BtnActionPerformed(evt);
            }
        });

        aLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLbl.setText("A");
        aLbl.setToolTipText("");

        bLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLbl.setText("B");
        bLbl.setToolTipText("");

        B3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3BtnActionPerformed(evt);
            }
        });

        B4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4BtnActionPerformed(evt);
            }
        });

        B5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5BtnActionPerformed(evt);
            }
        });

        B6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6BtnActionPerformed(evt);
            }
        });

        B7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7BtnActionPerformed(evt);
            }
        });

        B8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8BtnActionPerformed(evt);
            }
        });

        B2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2BtnActionPerformed(evt);
            }
        });

        B9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9BtnActionPerformed(evt);
            }
        });

        cLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cLbl.setText("C");

        C2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2BtnActionPerformed(evt);
            }
        });

        C3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3BtnActionPerformed(evt);
            }
        });

        C4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4BtnActionPerformed(evt);
            }
        });

        C5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5BtnActionPerformed(evt);
            }
        });

        C6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6BtnActionPerformed(evt);
            }
        });

        C7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7BtnActionPerformed(evt);
            }
        });

        C8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8BtnActionPerformed(evt);
            }
        });

        C9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9BtnActionPerformed(evt);
            }
        });

        dLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dLbl.setText("D");

        D2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2BtnActionPerformed(evt);
            }
        });

        D3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3BtnActionPerformed(evt);
            }
        });

        D4Btn.setToolTipText("");
        D4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4BtnActionPerformed(evt);
            }
        });

        D5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5BtnActionPerformed(evt);
            }
        });

        D6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6BtnActionPerformed(evt);
            }
        });

        D7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7BtnActionPerformed(evt);
            }
        });

        D8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D8BtnActionPerformed(evt);
            }
        });

        D9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D9BtnActionPerformed(evt);
            }
        });

        eLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eLbl.setText("E");
        eLbl.setToolTipText("");

        E2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2BtnActionPerformed(evt);
            }
        });

        E3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3BtnActionPerformed(evt);
            }
        });

        E4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4BtnActionPerformed(evt);
            }
        });

        E5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5BtnActionPerformed(evt);
            }
        });

        E6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6BtnActionPerformed(evt);
            }
        });

        E7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7BtnActionPerformed(evt);
            }
        });

        E8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E8BtnActionPerformed(evt);
            }
        });

        E9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E9BtnActionPerformed(evt);
            }
        });

        E10Btn.setToolTipText("");
        E10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E10BtnActionPerformed(evt);
            }
        });

        E1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1BtnActionPerformed(evt);
            }
        });

        fLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fLbl.setText("F");

        F1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1BtnActionPerformed(evt);
            }
        });

        F2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2BtnActionPerformed(evt);
            }
        });

        F3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3BtnActionPerformed(evt);
            }
        });

        F4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4BtnActionPerformed(evt);
            }
        });

        F5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5BtnActionPerformed(evt);
            }
        });

        F6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6BtnActionPerformed(evt);
            }
        });

        F7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F7BtnActionPerformed(evt);
            }
        });

        F8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F8BtnActionPerformed(evt);
            }
        });

        F9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F9BtnActionPerformed(evt);
            }
        });

        F10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F10BtnActionPerformed(evt);
            }
        });

        oneLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        oneLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneLbl.setText("1");
        oneLbl.setToolTipText("");

        twoLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        twoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twoLbl.setText("2");

        threeLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        threeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threeLbl.setText("3");

        fourLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fourLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourLbl.setText("4");

        fiveLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fiveLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiveLbl.setText("5");

        sixLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sixLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sixLbl.setText("6");

        tenLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tenLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenLbl.setText("10");
        tenLbl.setToolTipText("");

        nineLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nineLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nineLbl.setText("9");

        eightLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eightLbl.setText("8");

        sevenLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sevenLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevenLbl.setText("7");

        javax.swing.GroupLayout seatingPlanPanelLayout = new javax.swing.GroupLayout(seatingPlanPanel);
        seatingPlanPanel.setLayout(seatingPlanPanelLayout);
        seatingPlanPanelLayout.setHorizontalGroup(
            seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatingPlanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(screenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, seatingPlanPanelLayout.createSequentialGroup()
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(aLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(fLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(seatingPlanPanelLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(D2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(C2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, seatingPlanPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(F1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(E1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(oneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(E2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(F2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(twoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(A3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(C3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(E3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(F3Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(threeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(A4Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(B4Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(C4Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D4Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(E4Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(F4Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fourLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(A5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(B5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(D5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(E5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(F5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(A6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(B6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(C6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(E6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(F6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sixLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(seatingPlanPanelLayout.createSequentialGroup()
                                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(D7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(A7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(C7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(E7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(sevenLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eightLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(F8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(A8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(B8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(C8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(D8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(E8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(B9Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(C9Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D9Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(E9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(F9Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nineLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(150, 150, 150))
        );
        seatingPlanPanelLayout.setVerticalGroup(
            seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatingPlanPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(screenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(A6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(A7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(A4Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B9Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(B3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B4Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(C9Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(C2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C4Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(D8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(E1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E10Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(E2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E4Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E5Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E6Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E7Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E8Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E9Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(F1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(F9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(seatingPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fiveLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(oneLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fourLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nineLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eightLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevenLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sixLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBtn.setText("Select Tickets");
        backBtn.setToolTipText("");
        backBtn.setPreferredSize(new java.awt.Dimension(400, 60));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        finalizeBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        finalizeBtn.setText("View Booking");
        finalizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeBtnActionPerformed(evt);
            }
        });

        seatsLbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        seatsLbl.setText("Seats Selected: ");
        seatsLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(seatingPlanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(finalizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cinemaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinemaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(eventTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatingPlanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finalizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //If form being used to book tickets or to edit basket item...
        if (currentForm.equals("Booking Seating Plan") || currentForm.equals("Edit Booking Seating Plan")) {
            bookingTimer.cancel();

            //Sets secondsLeft in BookingTimer class to how long customer has left to book
            secondsLeft.setSecondsLeft(timeLeft);
            //Clears currently selected seats in Booking Class
            booking.emptySeats();
        }

        //If form being used to book tickets...
        if (currentForm.equals("Booking Seating Plan")) {
            current.setCurrentForm("Booking View 1"); //Sets currentForm in Current class to "Booking View 1"

            EventBookingUI eventBookingForm = new EventBookingUI(); //New EventBookingUI object created
            eventBookingForm.setVisible(true);
        }

        //If form being used to edit basket item...
        if (currentForm.equals("Edit Booking Seating Plan")) {
            current.setCurrentForm("Edit Booking 1");

            EventBookingUI eventBooking1Form = new EventBookingUI();
            eventBooking1Form.setVisible(true);
        }

        //If form being used to view booked seats...
        if (currentForm.equals("View Seating Plan")) {
            current.setCurrentForm("Customer Bookings");

            //New CustomerBookingsUI object created
            CustomerBookingsUI customerBookingsForm = new CustomerBookingsUI();
            customerBookingsForm.setVisible(true);
        }

        seatingPlanClock.stopClock();
        dispose(); //Current form disposed of
    }//GEN-LAST:event_backBtnActionPerformed

    private void finalizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeBtnActionPerformed
        //Stores number of tickets a customer is currently booking...
        int numTickets = booking.getNumTickets();

        //Stores currently selected seats as a comma separated String
        String seats = booking.getCurrentBookingSeatsString();
        //Stores currently selected seats as an array
        String[] allSeats = seats.split(",");
        //Stores number of seats currently selected
        int numSeatsSelected = allSeats.length;

        //If customer has selected a seat for every ticket they are booking...
        if (!(seats.equals("")) && (numSeatsSelected == numTickets)) {
            bookingTimer.cancel();
            seatingPlanClock.stopClock();

            //Sets secondsLeft in BookingTimer class to how long customer has left to book
            secondsLeft.setSecondsLeft(timeLeft);

            //If form being used to book tickets...
            if (currentForm.equals("Booking Seating Plan")) {
                current.setCurrentForm("Booking View 2"); //Sets currentForm in Current class to "Booking View 2"

                EventBookingUI eventBookingForm = new EventBookingUI(); //New EventBookingUI object created
                eventBookingForm.setVisible(true);
            }

            //If form being used to edit basket item...
            if (currentForm.equals("Edit Booking Seating Plan")) {
                current.setCurrentForm("Edit Booking 2");

                EventBookingUI editBooking2Form = new EventBookingUI();
                editBooking2Form.setVisible(true);
            }

            dispose(); //Current form disposed of
        } else { //If user has not selected a seat for every ticket they are booking...
            JOptionPane.showMessageDialog(null, "Please select all " + numTickets + " of your seats.", "Seats Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_finalizeBtnActionPerformed

    private void A3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3BtnActionPerformed
        booking.updateSeatingPlan(loa, 0, "A3", A3Btn, seatsLbl);
    }//GEN-LAST:event_A3BtnActionPerformed

    private void A4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4BtnActionPerformed
        booking.updateSeatingPlan(loa, 1, "A4", A4Btn, seatsLbl);
    }//GEN-LAST:event_A4BtnActionPerformed

    private void A5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5BtnActionPerformed
        booking.updateSeatingPlan(loa, 2, "A5", A5Btn, seatsLbl);
    }//GEN-LAST:event_A5BtnActionPerformed

    private void A6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6BtnActionPerformed
        booking.updateSeatingPlan(loa, 3, "A6", A6Btn, seatsLbl);
    }//GEN-LAST:event_A6BtnActionPerformed

    private void A7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7BtnActionPerformed
        booking.updateSeatingPlan(loa, 4, "A7", A7Btn, seatsLbl);
    }//GEN-LAST:event_A7BtnActionPerformed

    private void A8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8BtnActionPerformed
        booking.updateSeatingPlan(loa, 5, "A8", A8Btn, seatsLbl);
    }//GEN-LAST:event_A8BtnActionPerformed

    private void B2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2BtnActionPerformed
        booking.updateSeatingPlan(loa, 6, "B2", B2Btn, seatsLbl);
    }//GEN-LAST:event_B2BtnActionPerformed

    private void B3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3BtnActionPerformed
        booking.updateSeatingPlan(loa, 7, "B3", B3Btn, seatsLbl);
    }//GEN-LAST:event_B3BtnActionPerformed

    private void B4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4BtnActionPerformed
        booking.updateSeatingPlan(loa, 8, "B4", B4Btn, seatsLbl);
    }//GEN-LAST:event_B4BtnActionPerformed

    private void B5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5BtnActionPerformed
        booking.updateSeatingPlan(loa, 9, "B5", B5Btn, seatsLbl);
    }//GEN-LAST:event_B5BtnActionPerformed

    private void B6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6BtnActionPerformed
        booking.updateSeatingPlan(loa, 10, "B6", B6Btn, seatsLbl);
    }//GEN-LAST:event_B6BtnActionPerformed

    private void B7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7BtnActionPerformed
        booking.updateSeatingPlan(loa, 11, "B7", B7Btn, seatsLbl);
    }//GEN-LAST:event_B7BtnActionPerformed

    private void B8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8BtnActionPerformed
        booking.updateSeatingPlan(loa, 12, "B8", B8Btn, seatsLbl);
    }//GEN-LAST:event_B8BtnActionPerformed

    private void B9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9BtnActionPerformed
        booking.updateSeatingPlan(loa, 13, "B9", B9Btn, seatsLbl);
    }//GEN-LAST:event_B9BtnActionPerformed

    private void C2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2BtnActionPerformed
        booking.updateSeatingPlan(loa, 14, "C2", C2Btn, seatsLbl);
    }//GEN-LAST:event_C2BtnActionPerformed

    private void C3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3BtnActionPerformed
        booking.updateSeatingPlan(loa, 15, "C3", C3Btn, seatsLbl);
    }//GEN-LAST:event_C3BtnActionPerformed

    private void C4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4BtnActionPerformed
        booking.updateSeatingPlan(loa, 16, "C4", C4Btn, seatsLbl);
    }//GEN-LAST:event_C4BtnActionPerformed

    private void C5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5BtnActionPerformed
        booking.updateSeatingPlan(loa, 17, "C5", C5Btn, seatsLbl);
    }//GEN-LAST:event_C5BtnActionPerformed

    private void C6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6BtnActionPerformed
        booking.updateSeatingPlan(loa, 18, "C6", C6Btn, seatsLbl);
    }//GEN-LAST:event_C6BtnActionPerformed

    private void C7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7BtnActionPerformed
        booking.updateSeatingPlan(loa, 19, "C7", C7Btn, seatsLbl);
    }//GEN-LAST:event_C7BtnActionPerformed

    private void C8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8BtnActionPerformed
        booking.updateSeatingPlan(loa, 20, "C8", C8Btn, seatsLbl);
    }//GEN-LAST:event_C8BtnActionPerformed

    private void C9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9BtnActionPerformed
        booking.updateSeatingPlan(loa, 21, "C9", C9Btn, seatsLbl);
    }//GEN-LAST:event_C9BtnActionPerformed

    private void D2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2BtnActionPerformed
        booking.updateSeatingPlan(loa, 22, "D2", D2Btn, seatsLbl);
    }//GEN-LAST:event_D2BtnActionPerformed

    private void D3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3BtnActionPerformed
        booking.updateSeatingPlan(loa, 23, "D3", D3Btn, seatsLbl);
    }//GEN-LAST:event_D3BtnActionPerformed

    private void D4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4BtnActionPerformed
        booking.updateSeatingPlan(loa, 24, "D4", D4Btn, seatsLbl);
    }//GEN-LAST:event_D4BtnActionPerformed

    private void D5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5BtnActionPerformed
        booking.updateSeatingPlan(loa, 25, "D5", D5Btn, seatsLbl);
    }//GEN-LAST:event_D5BtnActionPerformed

    private void D6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6BtnActionPerformed
        booking.updateSeatingPlan(loa, 26, "D6", D6Btn, seatsLbl);
    }//GEN-LAST:event_D6BtnActionPerformed

    private void D7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7BtnActionPerformed
        booking.updateSeatingPlan(loa, 27, "D7", D7Btn, seatsLbl);
    }//GEN-LAST:event_D7BtnActionPerformed

    private void D8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D8BtnActionPerformed
        booking.updateSeatingPlan(loa, 28, "D8", D8Btn, seatsLbl);
    }//GEN-LAST:event_D8BtnActionPerformed

    private void D9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D9BtnActionPerformed
        booking.updateSeatingPlan(loa, 29, "D9", D9Btn, seatsLbl);
    }//GEN-LAST:event_D9BtnActionPerformed

    private void E1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1BtnActionPerformed
        booking.updateSeatingPlan(loa, 30, "E1", E1Btn, seatsLbl);
    }//GEN-LAST:event_E1BtnActionPerformed

    private void E2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2BtnActionPerformed
        booking.updateSeatingPlan(loa, 31, "E2", E2Btn, seatsLbl);
    }//GEN-LAST:event_E2BtnActionPerformed

    private void E3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3BtnActionPerformed
        booking.updateSeatingPlan(loa, 32, "E3", E3Btn, seatsLbl);
    }//GEN-LAST:event_E3BtnActionPerformed

    private void E4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4BtnActionPerformed
        booking.updateSeatingPlan(loa, 33, "E4", E4Btn, seatsLbl);
    }//GEN-LAST:event_E4BtnActionPerformed

    private void E5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5BtnActionPerformed
        booking.updateSeatingPlan(loa, 34, "E5", E5Btn, seatsLbl);
    }//GEN-LAST:event_E5BtnActionPerformed

    private void E6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6BtnActionPerformed
        booking.updateSeatingPlan(loa, 35, "E6", E6Btn, seatsLbl);
    }//GEN-LAST:event_E6BtnActionPerformed

    private void E7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E7BtnActionPerformed
        booking.updateSeatingPlan(loa, 36, "E7", E7Btn, seatsLbl);
    }//GEN-LAST:event_E7BtnActionPerformed

    private void E8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E8BtnActionPerformed
        booking.updateSeatingPlan(loa, 37, "E8", E8Btn, seatsLbl);
    }//GEN-LAST:event_E8BtnActionPerformed

    private void E9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E9BtnActionPerformed
        booking.updateSeatingPlan(loa, 38, "E9", E9Btn, seatsLbl);
    }//GEN-LAST:event_E9BtnActionPerformed

    private void E10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E10BtnActionPerformed
        booking.updateSeatingPlan(loa, 39, "E10", E10Btn, seatsLbl);
    }//GEN-LAST:event_E10BtnActionPerformed

    private void F1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1BtnActionPerformed
        booking.updateSeatingPlan(loa, 40, "F1", F1Btn, seatsLbl);
    }//GEN-LAST:event_F1BtnActionPerformed

    private void F2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2BtnActionPerformed
        booking.updateSeatingPlan(loa, 41, "F2", F2Btn, seatsLbl);
    }//GEN-LAST:event_F2BtnActionPerformed

    private void F3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3BtnActionPerformed
        booking.updateSeatingPlan(loa, 42, "F3", F3Btn, seatsLbl);
    }//GEN-LAST:event_F3BtnActionPerformed

    private void F4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4BtnActionPerformed
        booking.updateSeatingPlan(loa, 43, "F4", F4Btn, seatsLbl);
    }//GEN-LAST:event_F4BtnActionPerformed

    private void F5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5BtnActionPerformed
        booking.updateSeatingPlan(loa, 44, "F5", F5Btn, seatsLbl);
    }//GEN-LAST:event_F5BtnActionPerformed

    private void F6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6BtnActionPerformed
        booking.updateSeatingPlan(loa, 45, "F6", F6Btn, seatsLbl);
    }//GEN-LAST:event_F6BtnActionPerformed

    private void F7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F7BtnActionPerformed
        booking.updateSeatingPlan(loa, 46, "F7", F7Btn, seatsLbl);
    }//GEN-LAST:event_F7BtnActionPerformed

    private void F8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F8BtnActionPerformed
        booking.updateSeatingPlan(loa, 47, "F8", F8Btn, seatsLbl);
    }//GEN-LAST:event_F8BtnActionPerformed

    private void F9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F9BtnActionPerformed
        booking.updateSeatingPlan(loa, 48, "F9", F9Btn, seatsLbl);
    }//GEN-LAST:event_F9BtnActionPerformed

    private void F10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F10BtnActionPerformed
        booking.updateSeatingPlan(loa, 49, "F10", F10Btn, seatsLbl);
    }//GEN-LAST:event_F10BtnActionPerformed

    /**
     * Sets form features depending on forms current purpose
     */
    public void setFeatures() {
        //Stores current events title
        String currentEventTitle = current.getCurrentEventTitle();
        int numTickets; //Stores number of tickets a customer is currently booking

        //If form being used to book tickets or edit a basket item...
        if ((currentForm.equals("Booking Seating Plan")) || (currentForm.equals("Edit Booking Seating Plan"))) {
            //Initializes first frame of booking timer
            minutes = String.valueOf(timeLeft / 60);
            seconds = String.valueOf(timeLeft % 60);
            
            if (seconds.length() == 1) { //If seconds in single digits...
                seconds = 0 + seconds;
            }

            timerLbl.setText("Time Left: " + minutes + ":" + seconds);

            numTickets = booking.getNumTickets();
            eventTitleLbl.setText(currentEventTitle + " - " + numTickets + " Tickets");
        }

        //If form being used to view booked seats...
        if (currentForm.equals("View Seating Plan")) {
            titleLbl.setText("Customer Bookings");
            eventTitleLbl.setText(currentEventTitle);
            timerLbl.setText("");
            backBtn.setText("View Bookings");
            seatsLbl.setText("");
            finalizeBtn.setEnabled(false);
            finalizeBtn.setVisible(false);
        }
    }

    /**
     * Disables buttons representing previously booked seats
     * 
     * This prevents double bookings when the form functions as
     * the "Booking Seating Plan"/"Edit Booking Seating Plan" forms
     * and allows workers/managers to view the booked seats for an event
     * when the form functions as the "View Seating Plan" form
     */
    public void generateSeatingPlan() {
        //Stores primary key of current event
        String eventID = current.getCurrentEventID();
        //Stores all booked seats for current event as a "-" separated String
        String bookedSeats = search.getBookedSeats(eventID);
        //Stores all booked seats for current event as an array
        String[] allBookedSeats = bookedSeats.split("-");
        
        //Loops through array of booked seats, disabling
        //the buttons corresponding to the booked seats
        for (int i = 0; i < allBookedSeats.length; i++) {

            if (allBookedSeats[i].equals("A3")) {
                booking.disableBookedSeats(A3Btn);
            }
            if (allBookedSeats[i].equals("A4")) {
                booking.disableBookedSeats(A4Btn);
            }
            if (allBookedSeats[i].equals("A5")) {
                booking.disableBookedSeats(A5Btn);
            }
            if (allBookedSeats[i].equals("A6")) {
                booking.disableBookedSeats(A6Btn);
            }
            if (allBookedSeats[i].equals("A7")) {
                booking.disableBookedSeats(A7Btn);
            }
            if (allBookedSeats[i].equals("A8")) {
                booking.disableBookedSeats(A8Btn);
            }
            if (allBookedSeats[i].equals("B2")) {
                booking.disableBookedSeats(B2Btn);
            }
            if (allBookedSeats[i].equals("B3")) {
                booking.disableBookedSeats(B3Btn);
            }
            if (allBookedSeats[i].equals("B4")) {
                booking.disableBookedSeats(B4Btn);
            }
            if (allBookedSeats[i].equals("B5")) {
                booking.disableBookedSeats(B5Btn);
            }
            if (allBookedSeats[i].equals("B6")) {
                booking.disableBookedSeats(B6Btn);
            }
            if (allBookedSeats[i].equals("B7")) {
                booking.disableBookedSeats(B7Btn);
            }
            if (allBookedSeats[i].equals("B8")) {
                booking.disableBookedSeats(B8Btn);
            }
            if (allBookedSeats[i].equals("B9")) {
                booking.disableBookedSeats(B9Btn);
            }
            if (allBookedSeats[i].equals("C2")) {
                booking.disableBookedSeats(C2Btn);
            }
            if (allBookedSeats[i].equals("C3")) {
                booking.disableBookedSeats(C3Btn);
            }
            if (allBookedSeats[i].equals("C4")) {
                booking.disableBookedSeats(C4Btn);
            }
            if (allBookedSeats[i].equals("C5")) {
                booking.disableBookedSeats(C5Btn);
            }
            if (allBookedSeats[i].equals("C6")) {
                booking.disableBookedSeats(C6Btn);
            }
            if (allBookedSeats[i].equals("C7")) {
                booking.disableBookedSeats(C7Btn);
            }
            if (allBookedSeats[i].equals("C8")) {
                booking.disableBookedSeats(C8Btn);
            }
            if (allBookedSeats[i].equals("C9")) {
                booking.disableBookedSeats(C9Btn);
            }
            if (allBookedSeats[i].equals("D2")) {
                booking.disableBookedSeats(D2Btn);
            }
            if (allBookedSeats[i].equals("D3")) {
                booking.disableBookedSeats(D3Btn);
            }
            if (allBookedSeats[i].equals("D4")) {
                booking.disableBookedSeats(D4Btn);
            }
            if (allBookedSeats[i].equals("D5")) {
                booking.disableBookedSeats(D5Btn);
            }
            if (allBookedSeats[i].equals("D6")) {
                booking.disableBookedSeats(D6Btn);
            }
            if (allBookedSeats[i].equals("D7")) {
                booking.disableBookedSeats(D7Btn);
            }
            if (allBookedSeats[i].equals("D8")) {
                booking.disableBookedSeats(D8Btn);
            }
            if (allBookedSeats[i].equals("D9")) {
                booking.disableBookedSeats(D9Btn);
            }
            if (allBookedSeats[i].equals("E1")) {
                booking.disableBookedSeats(E1Btn);
            }
            if (allBookedSeats[i].equals("E2")) {
                booking.disableBookedSeats(E2Btn);
            }
            if (allBookedSeats[i].equals("E3")) {
                booking.disableBookedSeats(E3Btn);
            }
            if (allBookedSeats[i].equals("E4")) {
                booking.disableBookedSeats(E4Btn);
            }
            if (allBookedSeats[i].equals("E5")) {
                booking.disableBookedSeats(E5Btn);
            }
            if (allBookedSeats[i].equals("E6")) {
                booking.disableBookedSeats(E6Btn);
            }
            if (allBookedSeats[i].equals("E7")) {
                booking.disableBookedSeats(E7Btn);
            }
            if (allBookedSeats[i].equals("E8")) {
                booking.disableBookedSeats(E8Btn);
            }
            if (allBookedSeats[i].equals("E9")) {
                booking.disableBookedSeats(E9Btn);
            }
            if (allBookedSeats[i].equals("E10")) {
                booking.disableBookedSeats(E10Btn);
            }
            if (allBookedSeats[i].equals("F1")) {
                booking.disableBookedSeats(F1Btn);
            }
            if (allBookedSeats[i].equals("F2")) {
                booking.disableBookedSeats(F2Btn);
            }
            if (allBookedSeats[i].equals("F3")) {
                booking.disableBookedSeats(F3Btn);
            }
            if (allBookedSeats[i].equals("F4")) {
                booking.disableBookedSeats(F4Btn);
            }
            if (allBookedSeats[i].equals("F5")) {
                booking.disableBookedSeats(F5Btn);
            }
            if (allBookedSeats[i].equals("F6")) {
                booking.disableBookedSeats(F6Btn);
            }
            if (allBookedSeats[i].equals("F7")) {
                booking.disableBookedSeats(F7Btn);
            }
            if (allBookedSeats[i].equals("F8")) {
                booking.disableBookedSeats(F8Btn);
            }
            if (allBookedSeats[i].equals("F9")) {
                booking.disableBookedSeats(F9Btn);
            }
            if (allBookedSeats[i].equals("F10")) {
                booking.disableBookedSeats(F10Btn);
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatingPlanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatingPlanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatingPlanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatingPlanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatingPlanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A3Btn;
    private javax.swing.JButton A4Btn;
    private javax.swing.JButton A5Btn;
    private javax.swing.JButton A6Btn;
    private javax.swing.JButton A7Btn;
    private javax.swing.JButton A8Btn;
    private javax.swing.JButton B2Btn;
    private javax.swing.JButton B3Btn;
    private javax.swing.JButton B4Btn;
    private javax.swing.JButton B5Btn;
    private javax.swing.JButton B6Btn;
    private javax.swing.JButton B7Btn;
    private javax.swing.JButton B8Btn;
    private javax.swing.JButton B9Btn;
    private javax.swing.JButton C2Btn;
    private javax.swing.JButton C3Btn;
    private javax.swing.JButton C4Btn;
    private javax.swing.JButton C5Btn;
    private javax.swing.JButton C6Btn;
    private javax.swing.JButton C7Btn;
    private javax.swing.JButton C8Btn;
    private javax.swing.JButton C9Btn;
    private javax.swing.JButton D2Btn;
    private javax.swing.JButton D3Btn;
    private javax.swing.JButton D4Btn;
    private javax.swing.JButton D5Btn;
    private javax.swing.JButton D6Btn;
    private javax.swing.JButton D7Btn;
    private javax.swing.JButton D8Btn;
    private javax.swing.JButton D9Btn;
    private javax.swing.JButton E10Btn;
    private javax.swing.JButton E1Btn;
    private javax.swing.JButton E2Btn;
    private javax.swing.JButton E3Btn;
    private javax.swing.JButton E4Btn;
    private javax.swing.JButton E5Btn;
    private javax.swing.JButton E6Btn;
    private javax.swing.JButton E7Btn;
    private javax.swing.JButton E8Btn;
    private javax.swing.JButton E9Btn;
    private javax.swing.JButton F10Btn;
    private javax.swing.JButton F1Btn;
    private javax.swing.JButton F2Btn;
    private javax.swing.JButton F3Btn;
    private javax.swing.JButton F4Btn;
    private javax.swing.JButton F5Btn;
    private javax.swing.JButton F6Btn;
    private javax.swing.JButton F7Btn;
    private javax.swing.JButton F8Btn;
    private javax.swing.JButton F9Btn;
    private javax.swing.JLabel aLbl;
    private javax.swing.JLabel bLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cLbl;
    private javax.swing.JLabel cinemaLbl;
    private javax.swing.JLabel dLbl;
    private javax.swing.JLabel eLbl;
    private javax.swing.JLabel eightLbl;
    private javax.swing.JLabel eventTitleLbl;
    private javax.swing.JLabel fLbl;
    private javax.swing.JButton finalizeBtn;
    private javax.swing.JLabel fiveLbl;
    private javax.swing.JLabel fourLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nineLbl;
    private javax.swing.JLabel oneLbl;
    private javax.swing.JLabel screenLbl;
    private javax.swing.JPanel seatingPlanPanel;
    private javax.swing.JLabel seatsLbl;
    private javax.swing.JLabel sevenLbl;
    private javax.swing.JLabel sixLbl;
    private javax.swing.JLabel tenLbl;
    private javax.swing.JLabel threeLbl;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel timerLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel twoLbl;
    // End of variables declaration//GEN-END:variables
}
